version: '3'
services:
  postgres:
    image: "postgres"
    container_name: hasura-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dvdrental
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./dvd-rental.sql:/docker-entrypoint-initdb.d/init.sql
      - ./3055.dat:/docker-entrypoint-initdb.d/3055.dat
      - ./3057.dat:/docker-entrypoint-initdb.d/3057.dat
      - ./3059.dat:/docker-entrypoint-initdb.d/3059.dat
      - ./3061.dat:/docker-entrypoint-initdb.d/3061.dat
      - ./3062.dat:/docker-entrypoint-initdb.d/3062.dat
      - ./3063.dat:/docker-entrypoint-initdb.d/3063.dat
      - ./3065.dat:/docker-entrypoint-initdb.d/3065.dat
      - ./3067.dat:/docker-entrypoint-initdb.d/3067.dat
      - ./3069.dat:/docker-entrypoint-initdb.d/3069.dat
      - ./3071.dat:/docker-entrypoint-initdb.d/3071.dat
      - ./3073.dat:/docker-entrypoint-initdb.d/3073.dat
      - ./3075.dat:/docker-entrypoint-initdb.d/3075.dat
      - ./3077.dat:/docker-entrypoint-initdb.d/3077.dat
      - ./3079.dat:/docker-entrypoint-initdb.d/3079.dat
      - ./3081.dat:/docker-entrypoint-initdb.d/3081.dat
    restart: unless-stopped

  graphql-engine:
    image: hasura/graphql-engine:v1.1.0
    container_name: hasura-engine
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/dvdrental
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  database-data:
